const lessonData = {};

lessonData["01_LevYashin.mp3"] = [{
    text: "Lev Yashin was a famous football player from the Soviet Union. He was born in 1929. People called him the 'Black Spider' because he wore all-black clothes and was an amazing goalkeeper. Many fans think he is the best goalkeeper in football history. He played his whole career for one club, Dynamo Moscow. Yashin also played in four World Cups for his country. He won a very special award called the Ballon d'Or in 1963. He is still the only goalkeeper to win this big prize. Yashin was famous for stopping penalty kicks and for shouting loudly to organize his defenders. He changed how goalkeepers play the game. He died in 1990, but football fans all over the world still remember him today.",
    dict: { "famous": "ünlü", "Soviet Union": "Sovyetler Birliği", "born": "doğdu", "People": "insanlar", "called": "çağırdı/adlandırdı", "Spider": "Örümcek", "because": "çünkü", "wore": "giydi", "all-black": "tamamen siyah", "clothes": "kıyafetler", "amazing": "şaşırtıcı/harika", "goalkeeper": "kaleci", "Many": "birçok", "fans": "taraftarlar", "think": "düşünür", "best": "en iyi", "history": "tarih", "whole": "bütün/tüm", "career": "kariyer", "club": "kulüp", "also": "ayrıca", "played": "oynadı", "country": "ülke", "won": "kazandı", "special": "özel", "award": "ödül", "still": "hala", "only": "tek/sadece", "prize": "ödül", "stopping": "durdurma/kurtarma", "penalty kicks": "penaltı vuruşları", "shouting": "bağırma", "loudly": "yüksek sesle", "organize": "organize etmek", "defenders": "savunma oyuncuları", "changed": "değiştirdi", "game": "oyun/maç", "died": "öldü", "remember": "hatırlar", "today": "bugün" },
    questions: [ {q:"Was Lev Yashin from the Soviet Union?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people call him the 'Black Spider'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he wear all-black clothes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play his whole career for Dynamo Moscow?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the Ballon d'Or in 1963?", a_en:"Yes", a_tr:"Evet"}, {q:"Are there other goalkeepers who won this prize?", a_en:"No", a_tr:"Hayır"}, {q:"Did he change how goalkeepers play the game?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["02_GordonBanks.mp3"] = [{
    text: "Gordon Banks was a great English football player. He was born in 1937 in England. He played as a goalkeeper and is famous for being one of the best in the world. Banks played for Leicester City and Stoke City during his career. His most famous moment was in the 1966 World Cup. He helped the England national team win the tournament. This is still England's only World Cup win. Four years later, in the 1970 World Cup, he made a famous save against Pelé. People call it the 'save of the century.' Sadly, he lost the sight in his right eye after a car accident in 1972. This ended his top-level career. Banks was a fantastic player and a true gentleman of the sport.",
    dict: { "great": "harika/büyük", "English": "İngiliz", "goalkeeper": "kaleci", "famous": "ünlü", "best": "en iyi", "world": "dünya", "during": "sırasında", "moment": "an", "helped": "yardım etti", "national team": "milli takım", "win": "kazanmak", "tournament": "turnuva", "still": "hala", "only": "tek", "Four": "dört", "years": "yıllar", "later": "sonra", "made": "yaptı", "save": "kurtarış", "against": "karşı", "call": "adlandırır", "century": "yüzyıl", "Sadly": "ne yazık ki", "lost": "kaybetti", "sight": "görme yetisi", "right": "sağ", "eye": "göz", "after": "sonra", "car accident": "araba kazası", "ended": "bitirdi", "top-level": "üst düzey", "fantastic": "harika", "true": "gerçek", "gentleman": "beyefendi", "sport": "spor" },
    questions: [ {q:"Was Gordon Banks a great English football player?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help the England national team win the 1966 World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he make a famous save against Pelé?", a_en:"Yes", a_tr:"Evet"}, {q:"Do people call it the 'save of the century'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he lose the sight in his right eye?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his top-level career continue after the car accident?", a_en:"No", a_tr:"Hayır"}, {q:"Was he a fantastic player and a true gentleman?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["03_DinoZoff.mp3"] = [{
    text: "Dino Zoff is a famous Italian football player. He was born in 1942. He was a fantastic goalkeeper and a great leader on the pitch. Zoff played for big Italian clubs, but he is most famous for his time at Juventus. He won many league titles with them. The best moment of his career happened in 1982. He was the captain of the Italy national team when they won the World Cup. He was 40 years old at the time! This made him the oldest player ever to win the World Cup. Zoff was known for his calm personality and his excellent positioning. After he stopped playing, he became a successful football manager. He is a true legend in Italy and around the world.",
    dict: { "fantastic": "harika", "leader": "lider", "pitch": "saha", "clubs": "kulüpler", "most": "en", "time": "zaman/dönem", "won": "kazandı", "many": "birçok", "league": "lig", "titles": "şampiyonluklar", "best": "en iyi", "happened": "oldu/gerçekleşti", "captain": "kaptan", "oldest": "en yaşlı", "ever": "şimdiye kadar", "known": "bilinen", "calm": "sakin", "personality": "kişilik", "excellent": "mükemmel", "positioning": "pozisyon alma", "After": "sonra", "stopped": "bıraktı/durdu", "playing": "oynamayı", "became": "oldu", "successful": "başarılı", "manager": "menajer/teknik direktör", "true": "gerçek", "legend": "efsane", "around": "etrafında" },
    questions: [ {q:"Was Dino Zoff a famous Italian football player?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win many league titles with Juventus?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he the captain of the Italy national team in 1982?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a very young player when he won the World Cup?", a_en:"No", a_tr:"Hayır"}, {q:"Is he the oldest player ever to win the World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he known for his calm personality?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he become a successful football manager?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["04_FranzBeckenbauer.mp3"] = [{
    text: "Franz Beckenbauer was a legendary football player from Germany. He was born in 1945. Fans called him 'Der Kaiser,' which means 'The Emperor,' because he played like a smart leader. He played for Bayern Munich for many years and won many trophies. Beckenbauer was a defender, but he liked to run forward with the ball and start attacks. He invented a new position called the 'sweeper.' He won the World Cup with West Germany in 1974 as the team captain. Then, in 1990, he won the World Cup again as the manager of the German team. He is one of only three people to win the World Cup as both a player and a manager. He is a hero in German football history.",
    dict: { "legendary": "efsanevi", "Fans": "taraftarlar", "called": "adlandırdı", "Emperor": "İmparator", "means": "anlamına gelir", "smart": "akıllı", "trophies": "kupalar", "defender": "defans oyuncusu", "liked": "sevdi", "run": "koşmak", "forward": "ileriye", "ball": "top", "start": "başlatmak", "attacks": "hücumlar/saldırılar", "invented": "icat etti", "new": "yeni", "position": "pozisyon", "sweeper": "libero", "team captain": "takım kaptanı", "Then": "sonra", "again": "tekrar", "manager": "menajer/teknik direktör", "only": "sadece/tek", "three": "üç", "people": "insanlar", "both": "her ikisi", "hero": "kahraman", "history": "tarih" },
    questions: [ {q:"Was Franz Beckenbauer from Germany?", a_en:"Yes", a_tr:"Evet"}, {q:"Did fans call him 'The Emperor'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he like to run forward with the ball?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he invent a new position called the 'sweeper'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the World Cup as both a player and a manager?", a_en:"Yes", a_tr:"Evet"}, {q:"Are there many people who won the World Cup as both?", a_en:"No", a_tr:"Hayır"}, {q:"Is he a hero in German football history?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["05_BobbyMoore.mp3"] = [{
    text: "Bobby Moore was a famous English football player. He was born in 1941. He played as a defender and was known for being very smart on the pitch. He could read the game perfectly and stop attackers before they scored. Moore played most of his career for West Ham United in London. He is most famous for being the captain of the England national team. In 1966, he led England to win the World Cup at Wembley Stadium. Even the great Pelé said Bobby Moore was the fairest and best defender he ever played against. Moore was a calm leader and always showed respect to other players. Sadly, he died in 1993, but there is a famous statue of him outside Wembley Stadium today.",
    dict: { "known": "bilinen", "perfectly": "mükemmelce", "stop": "durdurmak", "attackers": "hücumcular", "before": "önce", "scored": "gol atmadan", "most": "çoğu", "career": "kariyer", "led": "yönetti/liderlik etti", "Stadium": "Stadyum", "Even": "hatta", "fairest": "en adil", "played": "oynadığı", "against": "karşı", "showed": "gösterdi", "respect": "saygı", "other": "diğer", "players": "oyuncular", "Sadly": "ne yazık ki", "died": "öldü", "statue": "heykel", "outside": "dışında", "today": "bugün" },
    questions: [ {q:"Was Bobby Moore a defender from England?", a_en:"Yes", a_tr:"Evet"}, {q:"Could he read the game perfectly?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he lead England to win the World Cup in 1966?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Pelé say Moore was the fairest defender?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he show no respect to other players?", a_en:"No", a_tr:"Hayır"}, {q:"Was he a calm leader?", a_en:"Yes", a_tr:"Evet"}, {q:"Is there a famous statue of him outside Wembley Stadium today?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["06_CarlosAlberto.mp3"] = [{
    text: "Carlos Alberto was a brilliant Brazilian football player. He was born in 1944. He played as a right-back, which is a defender who also helps the team attack. He played for famous clubs in Brazil like Santos, where he played with Pelé. Carlos Alberto was a strong leader and the captain of the Brazil national team. His most famous moment was in the 1970 World Cup final against Italy. He scored one of the most beautiful goals in football history. The whole team passed the ball, and Carlos Alberto ran very fast to kick it into the net. Brazil won the World Cup, and he proudly lifted the trophy. He showed the world how exciting a modern defender could be. He passed away in 2016.",
    dict: { "brilliant": "parlak/harika", "right-back": "sağ bek", "helps": "yardım eder", "attack": "hücum", "strong": "güçlü", "final": "final", "beautiful": "güzel", "passed": "paslaştı", "ran": "koştu", "fast": "hızlı", "kick": "vurmak", "net": "ağ/file", "proudly": "gururla", "lifted": "kaldırdı", "trophy": "kupa", "showed": "gösterdi", "exciting": "heyecan verici", "modern": "modern", "could be": "olabileceğini", "passed away": "vefat etti" },
    questions: [ {q:"Was Carlos Alberto a brilliant Brazilian football player?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play as a right-back?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he the captain of the Brazil national team?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score an ugly and boring goal in the 1970 final?", a_en:"No", a_tr:"Hayır"}, {q:"Did he run very fast to kick the ball into the net?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he proudly lift the World Cup trophy?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he show the world how exciting a modern defender could be?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["07_DanielPassarella.mp3"] = [{
    text: "Daniel Passarella is a famous football player from Argentina. He was born in 1953. He played as a central defender. Even though he was a short player for a defender, he was fantastic at jumping and heading the ball. Passarella was a tough player and a very strong leader. He played for River Plate in Argentina and later played in Italy. He is most famous for being the captain of the Argentina national team in 1978. He led his team to win their very first World Cup in front of their home fans. Passarella was also special because he scored a lot of goals. He scored free-kicks and penalty kicks. He is one of the best scoring defenders in the history of football.",
    dict: { "central": "merkez", "Even though": "rağmen", "short": "kısa", "jumping": "zıplama", "heading": "kafa vurma", "tough": "sert/zorlu", "later": "daha sonra", "led": "yönetti", "very first": "ilk defa", "in front of": "önünde", "home": "ev/kendi sahası", "special": "özel", "because": "çünkü", "a lot of": "çok", "free-kicks": "serbest vuruşlar", "penalty kicks": "penaltı vuruşları", "scoring": "gol atan" },
    questions: [ {q:"Was Daniel Passarella a central defender from Argentina?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a short player for a defender?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he fantastic at jumping and heading the ball?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a weak player with no leadership skills?", a_en:"No", a_tr:"Hayır"}, {q:"Did he lead Argentina to win their very first World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score a lot of goals for a defender?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score free-kicks and penalty kicks?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["08_GiacintoFacchetti.mp3"] = [{
    text: "Giacinto Facchetti was a legendary football player from Italy. He was born in 1942. He played as a left-back defender for Inter Milan. He spent his entire football career at this one club. Facchetti was very tall, fast, and strong. Before him, defenders usually stayed back to protect the goal. But Facchetti loved to run forward and help his team score goals. He was one of the first attacking full-backs in the world. He won many Italian league titles and European cups with Inter Milan. He was also the captain of the Italy national team and helped them win the European Championship in 1968. He was known for being a very fair and honest player. He died in 2006, and Inter Milan retired his number 3 shirt.",
    dict: { "left-back": "sol bek", "spent": "geçirdi", "entire": "bütün/tüm", "tall": "uzun", "Before": "öncesinde", "usually": "genellikle", "stayed back": "geride kalırdı", "protect": "korumak", "attacking": "hücum eden", "full-backs": "bekler", "fair": "adil", "honest": "dürüst", "retired": "emekli etti (numarayı)", "shirt": "forma" },
    questions: [ {q:"Did Giacinto Facchetti play as a left-back for Inter Milan?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he spend his entire career at this one club?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he very tall, fast, and strong?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he love to stay back and score no goals?", a_en:"No", a_tr:"Hayır"}, {q:"Was he one of the first attacking full-backs in the world?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he known for being a very fair and honest player?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Inter Milan retire his number 3 shirt?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["09_GaetanoScirea.mp3"] = [{
    text: "Gaetano Scirea was a wonderful Italian football player. He was born in 1953. He played as a defender, mostly in a position called a 'sweeper.' Scirea was famous for being very calm, polite, and elegant on the football pitch. Unlike many other defenders of his time, he played rough at no time and showed no anger. In his whole career, he received zero red cards! He played for Juventus for many years and won every major trophy with them. Scirea was also a key player for the Italy national team. He helped Italy win the World Cup in 1982. He was a quiet leader who organized the team beautifully. Tragically, he died in a car accident in 1989 when he was only 36 years old.",
    dict: { "wonderful": "harika", "mostly": "çoğunlukla", "position": "pozisyon", "polite": "kibar", "elegant": "zarif", "Unlike": "Aksine", "rough": "sert", "at no time": "hiçbir zaman", "showed": "gösterdi", "anger": "öfke", "received": "aldı", "zero": "sıfır", "red cards": "kırmızı kartlar", "major": "büyük/ana", "key": "kilit", "quiet": "sessiz", "organized": "organize etti", "beautifully": "güzelce", "Tragically": "trajik bir şekilde", "accident": "kaza" },
    questions: [ {q:"Was Gaetano Scirea a wonderful Italian football player?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he famous for being very calm, polite, and elegant?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play rough at no time?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he receive many red cards in his career?", a_en:"No", a_tr:"Hayır"}, {q:"Did he win every major trophy with Juventus?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a quiet leader who organized the team beautifully?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he die tragically in a car accident?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["10_RuudKrol.mp3"] = [{
    text: "Ruud Krol is a famous football player from the Netherlands. He was born in 1949. He played as a defender for the great Ajax team in the 1970s. Krol was an important part of a style called 'Total Football.' In this style, players could easily change positions during the game. Krol started as a left-back but later played as a central sweeper. He was very comfortable with the ball and could pass it beautifully with both feet. He won three European Cups in a row with Ajax. He also played for the Dutch national team and reached two World Cup finals in 1974 and 1978. Krol was a strong, stylish player who showed that defenders could be just as skilled as attackers.",
    dict: { "part": "parça/bölüm", "style": "stil/tarz", "easily": "kolayca", "change": "değiştirmek", "positions": "pozisyonlar", "started": "başladı", "comfortable": "rahat", "both feet": "her iki ayak", "in a row": "üst üste", "reached": "ulaştı/çıktı", "finals": "finaller", "stylish": "şık/tarz sahibi", "skilled": "yetenekli" },
    questions: [ {q:"Is Ruud Krol from the Netherlands?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he an important part of the 'Total Football' style?", a_en:"Yes", a_tr:"Evet"}, {q:"Could players in this style easily change positions?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he uncomfortable with the ball?", a_en:"No", a_tr:"Hayır"}, {q:"Could he pass the ball beautifully with both feet?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win three European Cups in a row with Ajax?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he reach two World Cup finals with the Dutch national team?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["11_EliasFigueroa.mp3"] = [{
    text: "Elias Figueroa was a great football player from Chile. He was born in 1946. He played as a central defender. Many people think he is the best player in the history of Chile. Figueroa played for clubs in Chile, Uruguay, and Brazil. He was very successful in Brazil with a team called Internacional. He was a very elegant and smart defender. He could read the game well and was very strong in the air. He was the captain of the Chile national team and played in three World Cups. He won the 'South American Footballer of the Year' award three times in a row. This is very rare for a defender. He is a true legend in South America.",
    dict: { "Chile": "Şili", "think": "düşünüyor", "successful": "başarılı", "elegant": "zarif", "read": "okumak", "air": "hava", "Year": "Yıl", "award": "ödül", "rare": "nadir", "true": "gerçek", "legend": "efsane", "South America": "Güney Amerika" },
    questions: [ {q:"Was Elias Figueroa a great football player from Chile?", a_en:"Yes", a_tr:"Evet"}, {q:"Do many people think he is the best player in the history of Chile?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he very strong in the air?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play in zero World Cups?", a_en:"No", a_tr:"Hayır"}, {q:"Did he win the 'South American Footballer of the Year' award three times in a row?", a_en:"Yes", a_tr:"Evet"}, {q:"Is winning this award three times rare for a defender?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he a true legend in South America?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["12_JohnCharles.mp3"] = [{
    text: "John Charles was a famous football player from Wales. He was born in 1931. He was very special because he could play as a central defender or a main striker. He was fantastic at both positions! He started his career at Leeds United in England and scored many goals. In 1957, he moved to Italy to play for Juventus. The Italian fans loved him. They called him 'Il Gigante Buono,' which means 'The Gentle Giant.' He was very tall and strong, but he caused harm to nobody. In his whole career, he received zero yellow or red cards. He played for Wales in the 1958 World Cup. He died in 2004, but fans still remember his great sportsmanship.",
    dict: { "Wales": "Galler", "main": "ana/temel", "striker": "forvet", "both": "her ikisi", "positions": "pozisyonlar", "Italian": "İtalyan", "Gentle": "Kibar/Nazik", "Giant": "Dev", "caused": "sebep oldu", "harm": "zarar", "nobody": "hiç kimse", "received": "aldı", "zero": "sıfır", "yellow": "sarı", "red": "kırmızı", "cards": "kartlar", "sportsmanship": "sportmenlik" },
    questions: [ {q:"Was John Charles a famous football player from Wales?", a_en:"Yes", a_tr:"Evet"}, {q:"Could he play as a central defender or a main striker?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Italian fans call him 'The Gentle Giant'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he cause harm to many players?", a_en:"No", a_tr:"Hayır"}, {q:"Did he receive zero yellow or red cards in his career?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play for Wales in the 1958 World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Do fans still remember his great sportsmanship?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["13_DiegoMaradona.mp3"] = [{
    text: "Diego Maradona was a football genius from Argentina. He was born in 1960. He was short but very strong, and he had amazing control of the ball. He played for Barcelona in Spain and Napoli in Italy. In Naples, the fans treated him like a king because he helped them win the Italian league. His most famous tournament was the 1986 World Cup in Mexico. He was the captain of Argentina and led them to become world champions. In one game against England, he scored two very famous goals. One was with his hand, called the 'Hand of God,' and the other was a beautiful solo run. Maradona had a difficult life off the pitch, but he is one of the greatest players ever. He died in 2020.",
    dict: { "genius": "dahi", "short": "kısa", "control": "kontrol", "treated": "davrandılar", "king": "kral", "led": "liderlik etti", "become": "olmak", "champions": "şampiyonlar", "hand": "el", "God": "Tanrı", "other": "diğeri", "solo": "tek başına", "run": "koşu", "difficult": "zor", "off": "dışında" },
    questions: [ {q:"Was Diego Maradona a football genius from Argentina?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he have amazing control of the ball?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the fans in Naples treat him like a king?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he lead Argentina to lose the 1986 World Cup?", a_en:"No", a_tr:"Hayır"}, {q:"Did he score a famous goal called the 'Hand of God'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score another goal with a beautiful solo run?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he considered one of the greatest players ever?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["14_MichelPlatini.mp3"] = [{
    text: "Michel Platini is a famous football player from France. He was born in 1955. He played as an attacking midfielder. He was a fantastic passer and scored many beautiful free-kicks. Platini played for Nancy and Saint-Étienne in France, but he became a global star at Juventus in Italy. He won the Ballon d'Or award three times in a row in the 1980s. He was the captain of the France national team. In 1984, he led France to win the European Championship and scored nine goals in the tournament! This is still a record today. After he stopped playing, he became a football manager and a very important leader in European football. He is a hero in French sports history.",
    dict: { "passer": "pasör", "free-kicks": "serbest vuruşlar", "global": "küresel", "star": "yıldız", "times": "kez", "in a row": "üst üste", "led": "yönetti", "nine": "dokuz", "record": "rekor", "manager": "menajer/teknik direktör", "important": "önemli", "leader": "lider" },
    questions: [ {q:"Did Michel Platini play as an attacking midfielder?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a fantastic passer who scored beautiful free-kicks?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the Ballon d'Or award three times in a row?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score zero goals in the 1984 European Championship?", a_en:"No", a_tr:"Hayır"}, {q:"Did he score nine goals in the 1984 tournament?", a_en:"Yes", a_tr:"Evet"}, {q:"Is his nine-goal tournament still a record today?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he become a football manager after he stopped playing?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["15_BobbyCharlton.mp3"] = [{
    text: "Bobby Charlton was a legendary English football player. He was born in 1937. He played as an attacking midfielder and was famous for his very hard shots from a long distance. He spent almost his whole career at Manchester United. In 1958, he survived a terrible airplane crash in Munich that killed many of his teammates. Charlton helped rebuild the team. Ten years later, he helped Manchester United win the European Cup. He was also a key player for the England national team. He won the World Cup with England in 1966 and won the Ballon d'Or in the same year. He was a true gentleman on and off the pitch. He passed away in 2023, leaving a great legacy.",
    dict: { "hard": "sert/zor", "shots": "şutlar", "long distance": "uzak mesafe", "spent": "geçirdi", "survived": "hayatta kaldı", "terrible": "korkunç", "airplane": "uçak", "crash": "kaza", "killed": "öldürdü", "teammates": "takım arkadaşları", "rebuild": "yeniden inşa etmek", "Ten": "on", "later": "sonra", "key": "kilit/önemli", "same": "aynı", "gentleman": "beyefendi", "leaving": "bırakarak", "legacy": "miras" },
    questions: [ {q:"Was Bobby Charlton famous for his very hard shots from a long distance?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he spend almost his whole career at Manchester United?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he survive a terrible airplane crash in Munich?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he refuse to help rebuild the team after the crash?", a_en:"No", a_tr:"Hayır"}, {q:"Did he help Manchester United win the European Cup ten years later?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the World Cup and the Ballon d'Or in 1966?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a true gentleman on and off the pitch?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["16_Zico.mp3"] = [{
    text: "Zico is a famous football player from Brazil. His real name is Arthur Antunes Coimbra. He was born in 1953. People often called him the 'White Pelé' because he was incredibly skilled. He played as an attacking midfielder and wore the famous number 10 shirt. He was a master at passing, dribbling, and taking free-kicks. Zico played most of his career for Flamengo in Brazil, where he scored hundreds of goals and won many trophies. He also played in Italy and Japan. Zico played for the Brazil national team in three World Cups. Even though he won no World Cups, many fans think his 1982 team was one of the best ever. He is a true icon of beautiful football.",
    dict: { "real": "gerçek", "often": "sık sık", "White": "Beyaz", "incredibly": "inanılmaz derecede", "skilled": "yetenekli", "wore": "giydi", "shirt": "forma", "master": "usta", "taking": "kullanma", "hundreds": "yüzlerce", "Even though": "rağmen", "icon": "ikon/sembol" },
    questions: [ {q:"Is Zico a famous football player from Brazil?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people often call him the 'White Pelé'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he wear the famous number 10 shirt?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he terrible at passing and taking free-kicks?", a_en:"No", a_tr:"Hayır"}, {q:"Did he play most of his career for Flamengo in Brazil?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play in three World Cups?", a_en:"Yes", a_tr:"Evet"}, {q:"Do many fans think his 1982 team was one of the best ever?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["17_GeorgeBest.mp3"] = [{
    text: "George Best was a wonderful football player from Northern Ireland. He was born in 1946. He played as a winger, mostly for Manchester United. Best was famous for his amazing dribbling skills. He could easily run past many defenders with the ball. In 1968, he helped Manchester United win the European Cup and he won the Ballon d'Or award. He was one of the first celebrity football players. He looked like a pop star and was very famous off the pitch too. Unfortunately, he had problems with alcohol, and his top-level career ended early. Even though his career was short, people who saw him play will forget his incredible talent at no point. He died in 2005.",
    dict: { "Northern Ireland": "Kuzey İrlanda", "mostly": "çoğunlukla", "easily": "kolayca", "run past": "yanından koşup geçmek", "celebrity": "ünlü", "looked": "görünüyordu", "pop star": "pop yıldızı", "off": "dışında", "Unfortunately": "ne yazık ki", "problems": "sorunlar", "alcohol": "alkol", "top-level": "üst düzey", "ended": "bitti", "early": "erken", "short": "kısa", "saw": "gördü", "forget": "unutmak", "talent": "yetenek", "at no point": "hiçbir zaman/noktada" },
    questions: [ {q:"Was George Best from Northern Ireland?", a_en:"Yes", a_tr:"Evet"}, {q:"Could he easily run past many defenders with the ball?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the Ballon d'Or award in 1968?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he look like a boring businessman?", a_en:"No", a_tr:"Hayır"}, {q:"Was he one of the first celebrity football players?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his top-level career end early?", a_en:"Yes", a_tr:"Evet"}, {q:"Will people who saw him play forget his talent at no point?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["18_Rivellino.mp3"] = [{
    text: "Rivellino is a famous football player from Brazil. He was born in 1946. He played as an attacking midfielder. He is very famous for his powerful left foot and his fantastic free-kicks. He also invented a very popular football trick called the 'flip flap' or 'elastico,' where a player moves the ball quickly from one side to the other. Rivellino played for Corinthians and Fluminense in Brazil. He was a very important player for the Brazil national team. He played in the 1970 World Cup and helped Brazil win the tournament with a legendary team. His big mustache and his powerful shots made him a favorite player for many fans around the world.",
    dict: { "powerful": "güçlü", "fantastic": "harika", "invented": "icat etti", "popular": "popüler", "trick": "numara", "flip flap": "çalım (elastico)", "moves": "hareket ettirir", "side": "taraf", "other": "diğer", "legendary": "efsanevi", "mustache": "bıyık", "favorite": "favori" },
    questions: [ {q:"Is Rivellino very famous for his powerful left foot?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he invent a football trick called the 'flip flap' or 'elastico'?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the trick move the ball quickly from one side to the other?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he refuse to play for the Brazil national team?", a_en:"No", a_tr:"Hayır"}, {q:"Did he play in the 1970 World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help Brazil win the tournament with a legendary team?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his big mustache and powerful shots make him a favorite player?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["19_Socrates.mp3"] = [{
    text: "Sócrates was a very unique football player from Brazil. He was born in 1954. He was very tall and played as an attacking midfielder. He was famous for his beautiful passes and his clever backheel kicks. He played mostly for Corinthians in Brazil. Sócrates was no mere football player; he was also a medical doctor! He was a very smart man who cared a lot about politics and democracy in his country. He was the captain of the famous Brazil national team in the 1982 World Cup. They suffered a loss in the end, but they played beautiful, attacking football. Sócrates was a leader on the pitch and a thinker off the pitch. He sadly died in 2011.",
    dict: { "unique": "eşsiz/benzersiz", "tall": "uzun", "clever": "zeki/akıllı", "backheel": "topuk", "kicks": "vuruşlar", "mere": "sadece/basit", "medical": "tıbbi", "doctor": "doktor", "cared": "önemsedi", "politics": "politika", "democracy": "demokrasi", "suffered": "yaşadı/katlandı", "loss": "kayıp/yenilgi", "thinker": "düşünür", "sadly": "ne yazık ki" },
    questions: [ {q:"Was Sócrates a very unique football player from Brazil?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he famous for his beautiful passes and clever backheel kicks?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he no mere football player, but also a medical doctor?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he care nothing about politics and democracy?", a_en:"No", a_tr:"Hayır"}, {q:"Was he the captain of the Brazil national team in the 1982 World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they play beautiful, attacking football?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a leader on the pitch and a thinker off the pitch?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["20_JohanNeeskens.mp3"] = [{
    text: "Johan Neeskens was a great football player from the Netherlands. He was born in 1951. He played as a midfielder. He was an essential part of the famous 'Total Football' teams of the 1970s. Neeskens was a very energetic and hardworking player. He ran all over the pitch, won the ball back, and scored goals too. He played with Johan Cruyff at Ajax in the Netherlands and Barcelona in Spain. He won three European Cups with Ajax. Neeskens also played in two World Cup finals for the Dutch national team in 1974 and 1978. In the 1974 final, he scored a famous penalty kick very early in the game. He was a strong and tireless player.",
    dict: { "essential": "esansiyel/önemli", "part": "parça", "energetic": "enerjik", "hardworking": "çalışkan", "ran": "koştu", "all over": "her yerinde", "won back": "geri kazandı", "scored": "gol attı", "early": "erken", "strong": "güçlü", "tireless": "yorulmak bilmez" },
    questions: [ {q:"Was Johan Neeskens from the Netherlands?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he an essential part of the 'Total Football' teams?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a very energetic and hardworking player?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he run all over the pitch to win the ball back?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win zero European Cups with Ajax?", a_en:"No", a_tr:"Hayır"}, {q:"Did he score a famous penalty kick early in the 1974 final?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a strong and tireless player?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["21_Didi.mp3"] = [{
    text: "Didi was a famous football player from Brazil. He was born in 1928. He played as a midfielder and was known for his elegant style. He was a very smart player who controlled the game with his passing. Didi is famous for inventing a special way to kick the ball called the 'falling leaf.' The ball goes up high and then drops suddenly into the goal. He played for Brazilian clubs like Botafogo and Fluminense, and also for Real Madrid in Spain. He was a very important player for the Brazil national team. He helped them win two World Cups in 1958 and 1962. Didi was a true artist on the football pitch. He died in 2001, but fans still remember his beautiful skills.",
    dict: { "known": "bilinen", "elegant": "zarif", "style": "stil", "controlled": "kontrol etti", "inventing": "icat etmesiyle", "special": "özel", "way": "yol/yöntem", "kick": "vurmak", "falling": "düşen", "leaf": "yaprak", "goes up": "yukarı çıkar", "high": "yüksek", "drops": "düşer", "suddenly": "aniden", "artist": "sanatçı", "remember": "hatırlar", "skills": "yetenekler" },
    questions: [ {q:"Was Didi a famous football player from Brazil?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he known for his elegant style?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he invent a special way to kick the ball called the 'falling leaf'?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the ball drop suddenly into the goal?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he fail to help his team win any World Cups?", a_en:"No", a_tr:"Hayır"}, {q:"Did he help Brazil win two World Cups?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a true artist on the football pitch?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["22_RaymondKopa.mp3"] = [{
    text: "Raymond Kopa was a great football player from France. He was born in 1931. He played as an attacking midfielder. He was a short player, but he was very fast and an amazing dribbler. Defenders struggled greatly to take the ball from him. Kopa played for Reims in France and then moved to Real Madrid in Spain. At Real Madrid, he played with other famous players and won the European Cup three times. In 1958, he won the Ballon d'Or award. He also played for the France national team in the 1958 World Cup. He helped his country finish in third place. Kopa was one of the first French football stars. He passed away in 2017.",
    dict: { "short": "kısa", "fast": "hızlı", "amazing": "harika", "dribbler": "top süren", "struggled": "zorlandı", "greatly": "büyük ölçüde", "take": "almak", "moved": "taşındı", "other": "diğer", "won": "kazandı", "finish": "bitirmek", "third": "üçüncü", "place": "sıra/yer", "stars": "yıldızlar", "passed away": "vefat etti" },
    questions: [ {q:"Was Raymond Kopa a great football player from France?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a short player but very fast?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he an amazing dribbler?", a_en:"Yes", a_tr:"Evet"}, {q:"Did defenders find it very easy to take the ball from him?", a_en:"No", a_tr:"Hayır"}, {q:"Did he win the European Cup three times with Real Madrid?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the Ballon d'Or award in 1958?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he one of the first French football stars?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["23_LuisSuarez.mp3"] = [{
    text: "Luis Suárez was a wonderful football player from Spain. He was born in 1935. He played as a midfielder and was famous for his beautiful, long passes. People called him 'The Architect' because he organized the game perfectly. He started his career at Barcelona in Spain and won the Ballon d'Or award in 1960. He is still the only male Spanish player to win this big prize. Later, he moved to Italy to play for Inter Milan. He helped Inter win many Italian leagues and two European Cups. He was also an important player for the Spain national team. He helped Spain win the European Championship in 1964. He died in 2023.",
    dict: { "wonderful": "harika", "long": "uzun", "passes": "paslar", "Architect": "Mimar", "organized": "organize etti", "perfectly": "mükemmelce", "started": "başladı", "still": "hala", "only": "tek", "male": "erkek", "prize": "ödül", "Later": "daha sonra", "moved": "taşındı", "leagues": "ligler", "Championship": "Şampiyona" },
    questions: [ {q:"Was Luis Suárez a wonderful football player from Spain?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he famous for his beautiful, long passes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people call him 'The Architect'?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he still the only male Spanish player to win the Ballon d'Or?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he refuse to play in Italy?", a_en:"No", a_tr:"Hayır"}, {q:"Did he help Inter Milan win two European Cups?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help Spain win the European Championship in 1964?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["24_GianniRivera.mp3"] = [{
    text: "Gianni Rivera is a famous football player from Italy. He was born in 1943. He played as an attacking midfielder. Italian fans called him the 'Golden Boy' because he was incredibly talented from a young age. He played almost his whole career for AC Milan. He was their captain for many years. Rivera was an elegant player who made perfect passes to the strikers. He helped AC Milan win many trophies, including Italian leagues and two European Cups. In 1969, he won the Ballon d'Or award. He also played for the Italy national team and won the European Championship in 1968. After he stopped playing, he became a politician in Italy.",
    dict: { "Golden": "Altın", "Boy": "Çocuk/Oğlan", "incredibly": "inanılmaz derecede", "talented": "yetenekli", "young": "genç", "age": "yaş", "almost": "neredeyse", "whole": "bütün/tüm", "elegant": "zarif", "made": "yaptı", "perfect": "mükemmel", "strikers": "forvetler", "including": "dahil olmak üzere", "politician": "politikacı" },
    questions: [ {q:"Did Italian fans call Gianni Rivera the 'Golden Boy'?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he incredibly talented from a young age?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play almost his whole career for AC Milan?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he make terrible passes to the strikers?", a_en:"No", a_tr:"Hayır"}, {q:"Did he help AC Milan win two European Cups?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the Ballon d'Or award in 1969?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he become a politician in Italy after he stopped playing?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["25_TeofiloCubillas.mp3"] = [{
    text: "Teófilo Cubillas is a legendary football player from Peru. He was born in 1949. He played as an attacking midfielder. Many people think he is the greatest Peruvian player in history. He was famous for his great technique, fast dribbling, and powerful free-kicks. Cubillas played in three World Cups for Peru. He played amazingly well and scored a total of 10 goals in World Cup tournaments. Very few midfielders have scored this many goals in the World Cup! He played for clubs in Peru, Switzerland, Portugal, and the United States. He was a very fair player and received zero red cards in his career. He is a true hero in his home country.",
    dict: { "legendary": "efsanevi", "Peru": "Peru", "greatest": "en büyük", "Peruvian": "Perulu", "technique": "teknik", "dribbling": "top sürme", "free-kicks": "serbest vuruşlar", "amazingly": "şaşırtıcı derecede", "total": "toplam", "Very few": "çok az", "fair": "adil", "received": "aldı", "zero": "sıfır", "red cards": "kırmızı kartlar", "hero": "kahraman" },
    questions: [ {q:"Is Teófilo Cubillas from Peru?", a_en:"Yes", a_tr:"Evet"}, {q:"Do many people think he is the greatest Peruvian player in history?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he famous for his great technique and fast dribbling?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score zero goals in World Cup tournaments?", a_en:"No", a_tr:"Hayır"}, {q:"Did he score a total of 10 goals in World Cup tournaments?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he receive zero red cards in his career?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he a true hero in his home country?", a_en:"Yes", a_tr:"Evet"} ]
}];lessonData["26_Falcao.mp3"] = [{
    text: "Paulo Roberto Falcão is a famous football player from Brazil. He was born in 1953. He played as a central midfielder. He was a very elegant and intelligent player. He always seemed to know exactly where the ball should go. Falcão started his career at Internacional in Brazil. Then, in 1980, he moved to Italy to play for AS Roma. The fans in Rome loved him so much that they called him the 'Eighth King of Rome.' He helped the team win the Italian league. Falcão also played for the Brazil national team in the 1982 World Cup. Even though Brazil failed to win, they played beautiful football, and Falcão was a key part of that famous team.",
    dict: { "famous": "ünlü", "central": "merkez", "midfielder": "orta saha", "elegant": "zarif", "intelligent": "zeki", "seemed": "göründü", "exactly": "tam olarak", "where": "nereye", "should go": "gitmeli", "started": "başladı", "career": "kariyer", "Then": "sonra", "moved": "taşındı", "fans": "taraftarlar", "loved": "sevdiler", "Eighth": "Sekizinci", "King": "Kral", "helped": "yardım etti", "league": "lig", "national team": "milli takım", "Even though": "rağmen", "failed": "başarısız oldu", "beautiful": "güzel", "key": "kilit", "part": "parça" },
    questions: [ {q:"Is Falcão a famous football player from Brazil?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play as a central midfielder?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a very elegant and intelligent player?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the fans in Rome call him the 'Eighth King of Rome'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help AS Roma win the Italian league?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Brazil win the 1982 World Cup?", a_en:"No", a_tr:"Hayır"}, {q:"Was he a key part of the famous 1982 Brazil team?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["27_Pele.mp3"] = [{
    text: "Pelé is one of the most famous football players in history. His real name was Edson Arantes do Nascimento. He was born in Brazil in 1940. He played as a forward and scored hundreds of goals during his career. People called him 'The King' of football. Pelé started playing for the Brazilian club Santos when he was just a teenager. He is most famous for his success with the Brazil national team. He is the only player ever to win three World Cups, in 1958, 1962, and 1970. He was fast, strong, and could shoot perfectly with both feet. He later played in the United States for the New York Cosmos to help make football popular there. He died in 2022.",
    dict: { "most": "en", "history": "tarih", "real": "gerçek", "forward": "forvet", "scored": "attı", "hundreds": "yüzlerce", "goals": "goller", "during": "sırasında", "career": "kariyer", "King": "Kral", "started": "başladı", "just": "sadece", "teenager": "genç", "success": "başarı", "national team": "milli takım", "only": "tek", "ever": "şimdiye kadar", "win": "kazanmak", "fast": "hızlı", "strong": "güçlü", "shoot": "şut çekmek", "perfectly": "mükemmelce", "both": "her ikisi", "feet": "ayaklar", "later": "daha sonra", "United States": "Amerika Birleşik Devletleri", "popular": "popüler", "died": "öldü" },
    questions: [ {q:"Is Pelé one of the most famous players in history?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people call him 'The King' of football?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score hundreds of goals during his career?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he the only player ever to win three World Cups?", a_en:"Yes", a_tr:"Evet"}, {q:"Could he shoot perfectly with both feet?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play in the United States to help make football popular?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win his first World Cup when he was fifty years old?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["28_JohanCruyff.mp3"] = [{
    text: "Johan Cruyff was a football genius from the Netherlands. He was born in 1947. He played as an attacking midfielder and forward. He was the star of a famous style called 'Total Football.' Cruyff was incredibly skilled and fast. He even invented a famous dribbling move called the 'Cruyff Turn,' which players still use today. He played for Ajax in the Netherlands and Barcelona in Spain. He won three European Cups with Ajax and won the Ballon d'Or award three times. He led the Dutch national team to the World Cup final in 1974. After playing, he became a brilliant manager and changed how Barcelona plays football. He passed away in 2016.",
    dict: { "genius": "dahi", "attacking": "hücuma dönük", "forward": "forvet", "star": "yıldız", "style": "stil", "called": "adlandırılan", "incredibly": "inanılmaz derecede", "skilled": "yetenekli", "fast": "hızlı", "invented": "icat etti", "dribbling": "top sürme", "move": "hareket", "Turn": "Dönüş", "still": "hala", "use": "kullanır", "won": "kazandı", "award": "ödül", "times": "kez", "led": "yönetti/taşıdı", "national team": "milli takım", "final": "final", "After": "sonra", "became": "oldu", "brilliant": "parlak/harika", "manager": "menajer", "changed": "değiştirdi", "how": "nasıl", "passed away": "vefat etti" },
    questions: [ {q:"Was Johan Cruyff a football genius from the Netherlands?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he the star of a style called 'Total Football'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he invent a dribbling move called the 'Cruyff Turn'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the Ballon d'Or award three times?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he lead the Dutch team to the World Cup final in 1974?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he become a terrible manager after playing?", a_en:"No", a_tr:"Hayır"}, {q:"Did he change how Barcelona plays football?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["29_AlfredoDiStefano.mp3"] = [{
    text: "Alfredo Di Stéfano was a legendary football player. He was born in Argentina in 1926. He is most famous for playing for Real Madrid in Spain. He was an amazing forward, but he could play almost anywhere on the pitch. He helped defend, controlled the midfield, and scored many goals. He was strong, fast, and very smart. Di Stéfano helped Real Madrid win the European Cup five times in a row in the 1950s. He scored a goal in every single final! He played for three different national teams during his career: Argentina, Colombia, and Spain. Many older football fans believe he is the most complete player in the history of the sport. He died in 2014.",
    dict: { "legendary": "efsanevi", "most": "en", "famous": "ünlü", "amazing": "şaşırtıcı/harika", "forward": "forvet", "almost": "neredeyse", "anywhere": "herhangi bir yer", "pitch": "saha", "helped": "yardım etti", "defend": "savunmak", "controlled": "kontrol etti", "midfield": "orta saha", "scored": "attı", "many": "birçok", "smart": "akıllı", "win": "kazanmak", "times": "kez", "in a row": "üst üste", "every": "her", "single": "tek", "final": "final", "different": "farklı", "national teams": "milli takımlar", "during": "sırasında", "career": "kariyer", "older": "daha yaşlı", "fans": "taraftarlar", "believe": "inanır", "complete": "eksiksiz/tam" },
    questions: [ {q:"Is Alfredo Di Stéfano most famous for playing for Real Madrid?", a_en:"Yes", a_tr:"Evet"}, {q:"Could he play almost anywhere on the pitch?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help Real Madrid win the European Cup five times in a row?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score a goal in every single European Cup final he played in?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play for three different national teams?", a_en:"Yes", a_tr:"Evet"}, {q:"Do many fans believe he is the most complete player in history?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play exclusively for one national team?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["30_FerencPuskas.mp3"] = [{
    text: "Ferenc Puskás was a fantastic football player from Hungary. He was born in 1927. He played as a forward and was famous for his incredibly powerful left foot. He scored many beautiful goals. Puskás was the captain of the great Hungarian national team in the 1950s. People called them the 'Mighty Magyars.' They suffered almost zero losses and reached the World Cup final in 1954. Later in his career, he moved to Spain and played for Real Madrid. He formed a deadly partnership with Alfredo Di Stéfano. Puskás won three European Cups with Real Madrid. Even though he was a little short and heavy, he was a true goal-scoring machine. He died in 2006.",
    dict: { "fantastic": "harika", "forward": "forvet", "incredibly": "inanılmaz derecede", "powerful": "güçlü", "left foot": "sol ayak", "scored": "attı", "beautiful": "güzel", "captain": "kaptan", "great": "büyük/harika", "national team": "milli takım", "Mighty": "Kudretli", "suffered": "yaşadı (acı)", "zero": "sıfır", "losses": "yenilgiler", "reached": "ulaştı/çıktı", "final": "final", "Later": "daha sonra", "career": "kariyer", "moved": "taşındı", "formed": "kurdu", "deadly": "ölümcül", "partnership": "ortaklık", "won": "kazandı", "Even though": "rağmen", "short": "kısa", "heavy": "ağır", "true": "gerçek", "machine": "makine" },
    questions: [ {q:"Was Ferenc Puskás from Hungary?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he famous for his incredibly powerful left foot?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the Hungarian team called the 'Mighty Magyars'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his team suffer almost zero losses in the 1950s?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he form a deadly partnership with Alfredo Di Stéfano?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he very tall and skinny?", a_en:"No", a_tr:"Hayır"}, {q:"Was he a true goal-scoring machine?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["31_Garrincha.mp3"] = [{
    text: "Garrincha was a magical football player from Brazil. He was born in 1933. His real name was Manuel Francisco dos Santos. 'Garrincha' means 'little bird' in Portuguese. He had a difficult childhood, and his legs were a bit crooked. His left leg was shorter than his right leg! But on the football pitch, he was amazing. He played as a right winger. He was famous for his incredible dribbling. Defenders knew nothing about which way he would run. He played most of his career for Botafogo in Brazil. Garrincha helped the Brazil national team win two World Cups in 1958 and 1962. When Pelé was injured in 1962, Garrincha became the star of the tournament. The Brazilian fans loved him very much and called him 'The Joy of the People.' He sadly died in 1983.",
    dict: { "magical": "sihirli/büyülü", "real": "gerçek", "means": "anlamına gelir", "bird": "kuş", "difficult": "zor", "childhood": "çocukluk", "crooked": "çarpık/eğri", "shorter": "daha kısa", "pitch": "saha", "amazing": "şaşırtıcı", "right winger": "sağ kanat", "incredible": "inanılmaz", "dribbling": "top sürme", "knew": "biliyordu", "nothing": "hiçbir şey", "way": "yol/yön", "most": "çoğu", "career": "kariyer", "helped": "yardım etti", "win": "kazanmak", "injured": "sakatlandı", "became": "oldu", "star": "yıldız", "tournament": "turnuva", "loved": "sevdi", "Joy": "Neşe", "People": "Halk/İnsanlar", "sadly": "ne yazık ki" },
    questions: [ {q:"Does 'Garrincha' mean 'little bird' in Portuguese?", a_en:"Yes", a_tr:"Evet"}, {q:"Was his left leg shorter than his right leg?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he famous for his incredible dribbling skills?", a_en:"Yes", a_tr:"Evet"}, {q:"Did defenders know nothing about which way he would run?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help Brazil win the World Cup in 1958 and 1962?", a_en:"Yes", a_tr:"Evet"}, {q:"When Pelé was injured, did Garrincha play terribly?", a_en:"No", a_tr:"Hayır"}, {q:"Did the fans call him 'The Joy of the People'?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["32_Eusebio.mp3"] = [{
    text: "Eusébio was a fantastic football player from Portugal. He was born in 1942 in Mozambique, which was a Portuguese colony in Africa. He played as a striker and was famous for his speed and his very powerful right foot. Fans called him the 'Black Panther' because he moved so fast and was so dangerous to defenders. Eusébio played almost his whole career for Benfica in Portugal. He helped them win many league titles and the European Cup in 1962. In 1965, he won the Ballon d'Or award. His most famous tournament was the 1966 World Cup in England. He scored nine goals and helped Portugal finish in third place. He was the top scorer of the tournament. Eusébio was a true gentleman of the game. He passed away in 2014.",
    dict: { "fantastic": "harika", "colony": "sömürge", "striker": "forvet", "famous": "ünlü", "speed": "hız", "powerful": "güçlü", "right foot": "sağ ayak", "Panther": "Panter", "moved": "hareket etti", "dangerous": "tehlikeli", "defenders": "defans oyuncuları", "almost": "neredeyse", "whole": "bütün", "career": "kariyer", "helped": "yardım etti", "win": "kazanmak", "league": "lig", "titles": "şampiyonluklar", "award": "ödül", "tournament": "turnuva", "scored": "attı", "finish": "bitirmek", "third": "üçüncü", "place": "sıra/yer", "top": "en üst", "scorer": "golcü", "true": "gerçek", "gentleman": "beyefendi", "passed away": "vefat etti" },
    questions: [ {q:"Was Eusébio born in Mozambique?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he famous for his speed and powerful right foot?", a_en:"Yes", a_tr:"Evet"}, {q:"Did fans call him the 'Black Panther'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play almost his whole career for Benfica?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the Ballon d'Or award in 1965?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score nine goals in the 1966 World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a very rude player on the pitch?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["33_GerdMuller.mp3"] = [{
    text: "Gerd Müller was a legendary football player from Germany. He was born in 1945. He played as a striker and is one of the best goalscorers in history. People called him 'Der Bomber' because he scored so many goals. He was a short player with an average speed, but he was incredibly strong. He always knew exactly where the ball would bounce inside the penalty area. Müller played most of his career for Bayern Munich. He helped them win many German league titles and three European Cups. He also played for the West Germany national team. He won the European Championship in 1972 and the World Cup in 1974. In the 1974 final, he scored the winning goal! He won the Ballon d'Or in 1970. He sadly died in 2021.",
    dict: { "legendary": "efsanevi", "striker": "forvet", "best": "en iyi", "goalscorers": "golcüler", "history": "tarih", "called": "adlandırdı", "scored": "attı", "short": "kısa", "average": "ortalama", "speed": "hız", "incredibly": "inanılmaz derecede", "strong": "güçlü", "knew": "biliyordu", "exactly": "tam olarak", "where": "nereye", "bounce": "sekmek", "inside": "içinde", "penalty area": "ceza sahası", "most": "çoğu", "career": "kariyer", "helped": "yardım etti", "win": "kazanmak", "league": "lig", "titles": "şampiyonluklar", "national team": "milli takım", "Championship": "Şampiyona", "final": "final", "winning": "kazandıran", "goal": "gol", "sadly": "ne yazık ki" },
    questions: [ {q:"Is Gerd Müller one of the best goalscorers in history?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people call him 'Der Bomber'?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a very tall and fast player?", a_en:"No", a_tr:"Hayır"}, {q:"Did he always know exactly where the ball would bounce?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play most of his career for Bayern Munich?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score the winning goal in the 1974 World Cup final?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the Ballon d'Or in 1970?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["34_Jairzinho.mp3"] = [{
    text: "Jairzinho is a famous football player from Brazil. He was born in 1944. He played as a fast and powerful winger. He was very strong and could easily run past defenders. He started his career at Botafogo in Brazil, the same club as his hero, Garrincha. Jairzinho is most famous for his time with the Brazil national team. He played in the 1970 World Cup in Mexico. That Brazilian team is one of the greatest teams ever. Jairzinho did something amazing in that tournament. He scored a goal in every single game! Brazil won the World Cup, and he became a national hero. Fans called him 'The Hurricane' because he was unstoppable on the pitch. He also played in France and helped make football popular there.",
    dict: { "fast": "hızlı", "powerful": "güçlü", "winger": "kanat oyuncusu", "easily": "kolayca", "run past": "yanından koşup geçmek", "defenders": "defans oyuncuları", "started": "başladı", "career": "kariyer", "same": "aynı", "club": "kulüp", "hero": "kahraman", "most": "en", "famous": "ünlü", "time": "zaman", "national team": "milli takım", "greatest": "en büyük", "ever": "şimdiye kadar", "amazing": "şaşırtıcı/harika", "tournament": "turnuva", "scored": "attı", "every": "her", "single": "tek", "game": "oyun/maç", "won": "kazandı", "became": "oldu", "Fans": "taraftarlar", "Hurricane": "Kasırga", "unstoppable": "durdurulamaz", "pitch": "saha", "popular": "popüler" },
    questions: [ {q:"Did Jairzinho play as a fast and powerful winger?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he start his career at Botafogo?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score a goal in every single game of the 1970 World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Brazil win the 1970 World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did fans call him 'The Hurricane'?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he very weak and slow on the pitch?", a_en:"No", a_tr:"Hayır"}, {q:"Did he help make football popular in France?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["35_PaoloRossi.mp3"] = [{
    text: "Paolo Rossi was a wonderful football player from Italy. He was born in 1956. He played as a striker. He was a small and quick player who was very smart near the goal. He always knew how to find open space to score. He played for Juventus and AC Milan in Italy. Rossi's most famous moment was the 1982 World Cup in Spain. Before the tournament, he had a difficult time and played zero games for two years. But in the World Cup, he was fantastic. He scored a famous hat-trick against a great Brazil team. Then he scored in the semi-final and the final. He helped Italy win the World Cup and became the top scorer. He also won the Ballon d'Or in 1982. He passed away in 2020.",
    dict: { "wonderful": "harika", "striker": "forvet", "small": "küçük", "quick": "hızlı", "smart": "akıllı", "near": "yakınında", "always": "her zaman", "knew": "biliyordu", "find": "bulmak", "open": "açık", "space": "alan", "score": "gol atmak", "famous": "ünlü", "moment": "an", "Before": "öncesinde", "tournament": "turnuva", "difficult": "zor", "zero": "sıfır", "games": "maçlar", "fantastic": "harika", "hat-trick": "üç gol", "against": "karşı", "Then": "sonra", "semi-final": "yarı final", "final": "final", "helped": "yardım etti", "win": "kazanmak", "became": "oldu", "top scorer": "gol kralı", "passed away": "vefat etti" },
    questions: [ {q:"Was Paolo Rossi a smart and quick striker?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he know how to find open space to score?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play zero games for two years before the 1982 World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score a famous hat-trick against Brazil?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score no goals in the final?", a_en:"No", a_tr:"Hayır"}, {q:"Did he help Italy win the World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he become the top scorer and win the Ballon d'Or?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["36_KarlHeinzRummenigge.mp3"] = [{
    text: "Karl-Heinz Rummenigge is a famous football player from Germany. He was born in 1955. He played as a forward. He was a very complete player. He was fast, strong, and could dribble very well. He also had a powerful shot. Rummenigge played for Bayern Munich for ten years. He helped them win many trophies, including two European Cups. He was so good that he won the Ballon d'Or award two times in a row, in 1980 and 1981. He also played for the West Germany national team. He helped his country win the European Championship in 1980. He played in two World Cup finals, in 1982 and 1986, but Germany suffered defeats both times. After he stopped playing, he became a very successful leader for Bayern Munich.",
    dict: { "forward": "forvet", "complete": "eksiksiz/tam", "fast": "hızlı", "strong": "güçlü", "dribble": "top sürmek", "powerful": "kuvvetli", "shot": "şut", "years": "yıllar", "helped": "yardım etti", "win": "kazanmak", "trophies": "kupalar", "including": "dahil olmak üzere", "award": "ödül", "times": "kez", "in a row": "üst üste", "national team": "milli takım", "country": "ülke", "Championship": "Şampiyona", "finals": "finaller", "suffered": "yaşadı/katlandı", "defeats": "yenilgiler", "both": "her ikisi", "After": "sonra", "stopped": "bıraktı/durdu", "playing": "oynamayı", "became": "oldu", "successful": "başarılı", "leader": "lider" },
    questions: [ {q:"Was Karl-Heinz Rummenigge a very complete forward?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play for Bayern Munich for ten years?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the Ballon d'Or award two times in a row?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help West Germany win the European Championship in 1980?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Germany win the World Cup finals in 1982 and 1986?", a_en:"No", a_tr:"Hayır"}, {q:"Did Germany suffer defeats in those two finals?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he become a successful leader for Bayern Munich later?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["37_KennyDalglish.mp3"] = [{
    text: "Kenny Dalglish is a legendary football player from Scotland. He was born in 1951. He played as a forward. Fans call him 'King Kenny' because he was so great. He started his career at Celtic in Scotland and won many league titles there. In 1977, he moved to Liverpool in England to replace Kevin Keegan. Dalglish was a very smart player. He scored many goals, but he also made many great passes for his teammates. He helped Liverpool become the best team in Europe. He won three European Cups with Liverpool. He also played for the Scotland national team and is their top scorer. Later, he became a manager for Liverpool and won even more trophies. He is a true hero for Liverpool fans.",
    dict: { "legendary": "efsanevi", "forward": "forvet", "Fans": "taraftarlar", "call": "adlandırır", "King": "Kral", "started": "başladı", "career": "kariyer", "won": "kazandı", "league": "lig", "titles": "şampiyonluklar", "moved": "taşındı", "replace": "yerine geçmek", "smart": "akıllı", "scored": "attı", "goals": "goller", "made": "yaptı", "great": "harika", "passes": "paslar", "teammates": "takım arkadaşları", "helped": "yardım etti", "become": "olmak", "best": "en iyi", "team": "takım", "national team": "milli takım", "top": "en üst", "scorer": "golcü", "Later": "daha sonra", "manager": "menajer", "even more": "daha da fazla", "trophies": "kupalar", "true": "gerçek", "hero": "kahraman" },
    questions: [ {q:"Do fans call him 'King Kenny'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he start his career at Celtic in Scotland?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he move to Liverpool to replace Kevin Keegan?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a very selfish player who made no passes?", a_en:"No", a_tr:"Hayır"}, {q:"Did he win three European Cups with Liverpool?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he the top scorer for the Scotland national team?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he become a manager for Liverpool later?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["38_KevinKeegan.mp3"] = [{
    text: "Kevin Keegan is a famous English football player. He was born in 1951. He played as a forward. He was a short player, but he was incredibly energetic and hardworking. He always ran very fast and gave up on nothing. Keegan started playing for Liverpool in the 1970s. He helped them win three English league titles and their first European Cup in 1977. Then, he did something unusual for English players. He moved to Germany to play for Hamburger SV. In Germany, he was fantastic. He won the Ballon d'Or award two times, in 1978 and 1979. He also played for the England national team and was their captain. Fans loved his exciting style of play and his famous curly hair.",
    dict: { "forward": "forvet", "short": "kısa", "incredibly": "inanılmaz derecede", "energetic": "enerjik", "hardworking": "çalışkan", "always": "her zaman", "ran": "koştu", "fast": "hızlı", "gave up": "pes etti/bıraktı", "nothing": "hiçbir şey", "started": "başladı", "helped": "yardım etti", "win": "kazanmak", "league": "lig", "titles": "şampiyonluklar", "first": "ilk", "unusual": "alışılmadık", "moved": "taşındı", "fantastic": "harika", "award": "ödül", "times": "kez", "national team": "milli takım", "captain": "kaptan", "loved": "sevdiler", "exciting": "heyecan verici", "style": "stil/tarz", "curly": "kıvırcık", "hair": "saç" },
    questions: [ {q:"Was Kevin Keegan a very energetic and hardworking player?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he run fast and give up on nothing?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help Liverpool win their first European Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he move to Germany to play for Hamburger SV?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the Ballon d'Or award zero times?", a_en:"No", a_tr:"Hayır"}, {q:"Was he the captain of the England national team?", a_en:"Yes", a_tr:"Evet"}, {q:"Did fans love his exciting style and curly hair?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["39_MarioKempes.mp3"] = [{
    text: "Mario Kempes is a great football player from Argentina. He was born in 1954. He played as a striker and was famous for his powerful runs and strong left foot. He started his career in Argentina, but he became a star playing for Valencia in Spain. He scored many goals for Valencia and helped them win European trophies. Kempes is a huge hero in Argentina because of the 1978 World Cup. The tournament was played in Argentina. Kempes was the star of the team. He scored six goals in the tournament, including two goals in the final against the Netherlands. He was the top scorer and helped Argentina win their first World Cup. He showed incredible passion and energy on the pitch.",
    dict: { "striker": "forvet", "famous": "ünlü", "powerful": "güçlü", "runs": "koşular", "strong": "kuvvetli", "left foot": "sol ayak", "started": "başladı", "career": "kariyer", "became": "oldu", "star": "yıldız", "scored": "attı", "goals": "goller", "helped": "yardım etti", "win": "kazanmak", "trophies": "kupalar", "huge": "büyük", "hero": "kahraman", "because of": "yüzünden", "tournament": "turnuva", "played": "oynandı", "team": "takım", "including": "dahil olmak üzere", "final": "final", "against": "karşı", "top": "en üst", "scorer": "golcü", "first": "ilk", "showed": "gösterdi", "incredible": "inanılmaz", "passion": "tutku", "energy": "enerji", "pitch": "saha" },
    questions: [ {q:"Was Mario Kempes famous for his powerful runs and strong left foot?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he become a star playing for Valencia in Spain?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the 1978 World Cup played in Argentina?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score zero goals in the tournament?", a_en:"No", a_tr:"Hayır"}, {q:"Did he score two goals in the final against the Netherlands?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help Argentina win their first World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he show incredible passion and energy on the pitch?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["40_SandorKocsis.mp3"] = [{
    text: "Sándor Kocsis was a brilliant football player from Hungary. He was born in 1929. He played as a striker and was part of the famous 'Mighty Magyars' team of the 1950s. He played with Ferenc Puskás. Kocsis was incredible at heading the ball. People called him the 'Man with the Golden Head.' He could jump very high and score beautiful goals with his head. He was the top scorer in the 1954 World Cup in Switzerland. He scored 11 goals in just five games! This is an amazing record. Sadly, Hungary lost the final to West Germany. Later in his career, he moved to Spain and played for Barcelona. He helped them win many Spanish league titles. He died tragically in 1979.",
    dict: { "brilliant": "parlak/harika", "striker": "forvet", "part": "parça/üye", "famous": "ünlü", "Mighty": "Kudretli", "incredible": "inanılmaz", "heading": "kafa vurma", "ball": "top", "called": "adlandırdı", "Man": "Adam", "Golden": "Altın", "Head": "Kafa", "jump": "zıplamak", "high": "yüksek", "score": "gol atmak", "beautiful": "güzel", "goals": "goller", "top": "en üst", "scorer": "golcü", "just": "sadece", "games": "maçlar", "amazing": "şaşırtıcı", "record": "rekor", "Sadly": "ne yazık ki", "lost": "kaybetti", "final": "final", "Later": "daha sonra", "career": "kariyer", "moved": "taşındı", "helped": "yardım etti", "win": "kazanmak", "league": "lig", "titles": "şampiyonluklar", "died": "öldü", "tragically": "trajik bir şekilde" },
    questions: [ {q:"Was Sándor Kocsis part of the 'Mighty Magyars' team?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he incredible at heading the ball?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people call him the 'Man with the Golden Head'?", a_en:"Yes", a_tr:"Evet"}, {q:"Could he jump very high to score?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score 11 goals in just five games in 1954?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Hungary win the 1954 World Cup final?", a_en:"No", a_tr:"Hayır"}, {q:"Did he help Barcelona win many Spanish league titles?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["41_JustFontaine.mp3"] = [{
    text: "Just Fontaine was a famous football player from France. He was born in 1933. He played as a striker and was an incredible goalscorer. Fontaine is most famous for his amazing performance in the 1958 World Cup in Sweden. In just six games, he scored 13 goals! This is still the record for the most goals scored by one player in a single World Cup tournament. Nobody has ever broken this record. He played mostly for a French club called Reims and helped them reach the European Cup final. Sadly, he had a very bad leg injury and had to stop playing football when he was only 28 years old. Even though his career was short, he is a true football legend. He died in 2023.",
    dict: { "striker": "forvet", "incredible": "inanılmaz", "goalscorer": "golcü", "most": "en", "amazing": "şaşırtıcı", "performance": "performans", "just": "sadece", "games": "maçlar", "scored": "attı", "still": "hala", "record": "rekor", "player": "oyuncu", "single": "tek", "tournament": "turnuva", "Nobody": "hiç kimse", "ever": "şimdiye kadar", "broken": "kırdı", "mostly": "çoğunlukla", "club": "kulüp", "called": "adlandırılan", "helped": "yardım etti", "reach": "ulaşmak", "final": "final", "Sadly": "ne yazık ki", "bad": "kötü", "leg": "bacak", "injury": "sakatlık", "stop": "durmak/bırakmak", "playing": "oynamayı", "only": "sadece", "years old": "yaşında", "Even though": "rağmen", "career": "kariyer", "short": "kısa", "true": "gerçek", "legend": "efsane", "died": "öldü" },
    questions: [ {q:"Was Just Fontaine an incredible goalscorer from France?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score 13 goals in the 1958 World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Has nobody ever broken his World Cup record?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help the club Reims reach the European Cup final?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play professional football until he was forty years old?", a_en:"No", a_tr:"Hayır"}, {q:"Did a bad leg injury force him to stop playing?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he considered a true football legend?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["42_GiuseppeMeazza.mp3"] = [{
    text: "Giuseppe Meazza was a legendary football player from Italy. He was born in 1910. He played as a forward and was famous for his amazing dribbling and shooting skills. Fans loved watching him because he played beautifully. Meazza played most of his career for Inter Milan. He scored 242 goals for them! He was also the star of the Italy national team. He helped Italy win the World Cup two times in a row, in 1934 and 1938. He was the captain of the 1938 team. He was very famous and was one of the first football players to have personal sponsors. Today, the huge football stadium in Milan is named the Stadio Giuseppe Meazza in his honor. He passed away in 1979.",
    dict: { "legendary": "efsanevi", "forward": "forvet", "famous": "ünlü", "amazing": "harika", "dribbling": "top sürme", "shooting": "şut çekme", "skills": "yetenekler", "loved": "sevdi", "watching": "izlemeyi", "because": "çünkü", "beautifully": "güzelce", "most": "çoğu", "career": "kariyer", "scored": "attı", "goals": "goller", "star": "yıldız", "national team": "milli takım", "helped": "yardım etti", "win": "kazanmak", "times": "kez", "in a row": "üst üste", "captain": "kaptan", "first": "ilk", "personal": "kişisel", "sponsors": "sponsorlar", "Today": "bugün", "huge": "kocaman", "stadium": "stadyum", "named": "isimlendirilmiş", "honor": "onur", "passed away": "vefat etti" },
    questions: [ {q:"Was Giuseppe Meazza a legendary player from Italy?", a_en:"Yes", a_tr:"Evet"}, {q:"Did fans love watching him play beautifully?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score 242 goals for Inter Milan?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help Italy win the World Cup two times in a row?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he the captain of the 1938 Italy team?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he have zero personal sponsors?", a_en:"No", a_tr:"Hayır"}, {q:"Is the huge football stadium in Milan named in his honor?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["43_StanleyMatthews.mp3"] = [{
    text: "Stanley Matthews was a very special football player from England. He was born in 1915. He played as an outside right winger. People called him 'The Wizard of the Dribble' because he could keep the ball away from defenders so easily. He played for Stoke City and Blackpool. The most amazing thing about Matthews was his long career. He took very good care of his body and ate healthy food. Because of this, he played professional football until he was 50 years old! In 1956, he won the very first Ballon d'Or award. He also played for the England national team many times. He was a very fair player and received zero yellow or red cards. He died in 2000.",
    dict: { "special": "özel", "outside right": "sağ açık", "winger": "kanat oyuncusu", "called": "adlandırdı", "Wizard": "Büyücü", "Dribble": "Top sürme", "keep": "tutmak", "ball": "top", "away": "uzakta", "defenders": "defans oyuncuları", "easily": "kolayca", "most": "en", "amazing": "şaşırtıcı", "thing": "şey", "long": "uzun", "career": "kariyer", "took care": "bakım yaptı/ilgilendi", "body": "vücut", "ate": "yedi", "healthy": "sağlıklı", "food": "yiyecek", "Because of": "yüzünden/sayesinde", "professional": "profesyonel", "until": "kadar", "years old": "yaşında", "won": "kazandı", "very first": "ilk defa/en ilk", "award": "ödül", "national team": "milli takım", "times": "kez", "fair": "adil", "received": "aldı", "zero": "sıfır", "yellow": "sarı", "red": "kırmızı", "cards": "kartlar" },
    questions: [ {q:"Did people call him 'The Wizard of the Dribble'?", a_en:"Yes", a_tr:"Evet"}, {q:"Could he keep the ball away from defenders easily?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he take very good care of his body and eat healthy food?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play professional football until he was 50 years old?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the very first Ballon d'Or award in 1956?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he receive many yellow and red cards?", a_en:"No", a_tr:"Hayır"}, {q:"Was he a very fair player?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["44_TomFinney.mp3"] = [{
    text: "Tom Finney was a wonderful English football player. He was born in 1922. He played as a forward or a winger. He was famous for being very loyal to his hometown club. He played his entire professional career for Preston North End. Fans loved him very much and called him the 'Preston Plumber' because his family had a plumbing business. Finney was a fantastic dribbler and could cross the ball perfectly to his teammates. He played for the England national team in three World Cups. Many players who played against him said he was one of the hardest attackers to stop. After he stopped playing, he did a lot of charity work for his community. He was a true gentleman. He passed away in 2014.",
    dict: { "wonderful": "harika", "forward": "forvet", "winger": "kanat oyuncusu", "famous": "ünlü", "loyal": "sadık", "hometown": "memleket", "club": "kulüp", "entire": "bütün/tüm", "professional": "profesyonel", "career": "kariyer", "Fans": "taraftarlar", "loved": "sevdi", "called": "adlandırdı", "Plumber": "Tesisatçı", "because": "çünkü", "family": "aile", "plumbing": "tesisat", "business": "iş", "fantastic": "harika", "dribbler": "top süren", "cross": "orta yapmak", "ball": "top", "perfectly": "mükemmelce", "teammates": "takım arkadaşları", "national team": "milli takım", "against": "karşı", "said": "dedi", "hardest": "en zor", "attackers": "hücumcular", "stop": "durdurmak", "After": "sonra", "stopped": "bıraktı", "charity work": "hayır işi", "community": "toplum", "true": "gerçek", "gentleman": "beyefendi", "passed away": "vefat etti" },
    questions: [ {q:"Was Tom Finney very loyal to his hometown club?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play his entire career for Preston North End?", a_en:"Yes", a_tr:"Evet"}, {q:"Did fans call him the 'Preston Plumber'?", a_en:"Yes", a_tr:"Evet"}, {q:"Could he cross the ball perfectly to his teammates?", a_en:"Yes", a_tr:"Evet"}, {q:"Did players say he was very easy to stop?", a_en:"No", a_tr:"Hayır"}, {q:"Did he do a lot of charity work after he stopped playing?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a true gentleman?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["45_GunnarNordahl.mp3"] = [{
    text: "Gunnar Nordahl was a great football player from Sweden. He was born in 1921. He played as a strong and powerful striker. He started his career in Sweden, but he is most famous for playing in Italy. In 1949, he moved to AC Milan. He was incredibly successful there. Nordahl was the top scorer in the Italian league five times! This is a record that still stands today. He scored 210 goals in the Italian league, which makes him one of the best goalscorers in Italy's history. He also played for the Sweden national team and helped them win a gold medal at the 1948 Olympic Games. He was a very physical player who always found a way to score. He died in 1995.",
    dict: { "great": "harika/büyük", "strong": "güçlü", "powerful": "kuvvetli", "striker": "forvet", "started": "başladı", "career": "kariyer", "most": "en", "famous": "ünlü", "moved": "taşındı", "incredibly": "inanılmaz derecede", "successful": "başarılı", "there": "orada", "top scorer": "gol kralı", "league": "lig", "times": "kez", "record": "rekor", "still": "hala", "stands": "duruyor/geçerli", "scored": "attı", "goals": "goller", "makes": "yapar", "best": "en iyi", "history": "tarih", "national team": "milli takım", "helped": "yardım etti", "win": "kazanmak", "gold medal": "altın madalya", "Olympic Games": "Olimpiyat Oyunları", "physical": "fiziksel", "always": "her zaman", "found": "buldu", "way": "yol", "score": "gol atmak" },
    questions: [ {q:"Was Gunnar Nordahl a strong and powerful striker from Sweden?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he most famous for playing in Italy for AC Milan?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he the top scorer in the Italian league five times?", a_en:"Yes", a_tr:"Evet"}, {q:"Does his record for top scorer still stand today?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help Sweden win a gold medal at the 1948 Olympic Games?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a very weak player who struggled to score?", a_en:"No", a_tr:"Hayır"}, {q:"Did he always find a way to score goals?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["46_FranciscoGento.mp3"] = [{
    text: "Francisco Gento was a legendary football player from Spain. He was born in 1933. He played as a left winger. He was incredibly fast, and defenders could almost never catch him. Fans called him the 'Cantabrian Gale' because he ran like the wind. Gento played almost his whole career for Real Madrid. He played with other greats like Di Stéfano and Puskás. Gento holds a very special record in football history. He won the European Cup six times! No other player has won it more times than him. He also won the Spanish league 12 times with Real Madrid. He played for the Spain national team in two World Cups. He passed away in 2022.",
    dict: { "legendary": "efsanevi", "left winger": "sol kanat", "incredibly": "inanılmaz derecede", "fast": "hızlı", "defenders": "defans oyuncuları", "almost": "neredeyse", "catch": "yakalamak", "Fans": "taraftarlar", "called": "adlandırdı", "Gale": "Fırtına", "because": "çünkü", "ran": "koştu", "wind": "rüzgar", "whole": "bütün/tüm", "career": "kariyer", "other": "diğer", "greats": "büyükler", "holds": "elinde tutar", "special": "özel", "record": "rekor", "history": "tarih", "won": "kazandı", "times": "kez", "No other": "hiçbir diğer", "player": "oyuncu", "more": "daha fazla", "league": "lig", "national team": "milli takım", "passed away": "vefat etti" },
    questions: [ {q:"Was Francisco Gento incredibly fast?", a_en:"Yes", a_tr:"Evet"}, {q:"Did fans call him the 'Cantabrian Gale' because he ran like the wind?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play almost his whole career for Real Madrid?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the European Cup six times?", a_en:"Yes", a_tr:"Evet"}, {q:"Have many other players won the European Cup more times than him?", a_en:"No", a_tr:"Hayır"}, {q:"Did he win the Spanish league 12 times?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play for Spain in two World Cups?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["47_SandroMazzola.mp3"] = [{
    text: "Sandro Mazzola is a famous football player from Italy. He was born in 1942. He played as an attacking midfielder or a forward. His father, Valentino Mazzola, was also a very famous football player who died in a tragic plane crash. Sandro became a legend like his father. He played his entire career for Inter Milan. In the 1960s, he was the star of a great Inter Milan team. He helped them win the European Cup two times in a row, in 1964 and 1965. He also played for the Italy national team. He helped Italy win the European Championship in 1968 and reach the World Cup final in 1970. Mazzola was known for his speed, smart passing, and important goals.",
    dict: { "famous": "ünlü", "attacking": "hücuma dönük", "midfielder": "orta saha", "forward": "forvet", "father": "baba", "also": "ayrıca", "died": "öldü", "tragic": "trajik", "plane crash": "uçak kazası", "became": "oldu", "legend": "efsane", "entire": "bütün/tüm", "career": "kariyer", "star": "yıldız", "great": "harika", "team": "takım", "helped": "yardım etti", "win": "kazanmak", "times": "kez", "in a row": "üst üste", "national team": "milli takım", "Championship": "Şampiyona", "reach": "ulaşmak", "final": "final", "known": "bilinirdi", "speed": "hız", "smart": "akıllı", "passing": "pas verme", "important": "önemli", "goals": "goller" },
    questions: [ {q:"Was Sandro Mazzola an attacking midfielder or forward?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his famous father die in a tragic plane crash?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Sandro play his entire career for Inter Milan?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help Inter Milan win the European Cup two times in a row?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help Italy win the European Championship in 1968?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he known for being very slow and making bad passes?", a_en:"No", a_tr:"Hayır"}, {q:"Was he known for his speed and important goals?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["48_UweSeeler.mp3"] = [{
    text: "Uwe Seeler was a beloved football player from Germany. He was born in 1936. He played as a striker. He was a short player, but he was incredibly strong and fantastic at heading the ball. Seeler was famous for scoring difficult goals, even bicycle kicks! He played his entire club career for Hamburger SV in Germany. He was extremely loyal to his club and refused offers from richer teams in Italy and Spain. He was also the captain of the West Germany national team. He played in four World Cups and reached the final in 1966. Even though he won zero World Cups, he is a massive hero in Germany because of his sportsmanship and warm personality. He passed away in 2022.",
    dict: { "beloved": "sevilen", "striker": "forvet", "short": "kısa", "incredibly": "inanılmaz derecede", "strong": "güçlü", "fantastic": "harika", "heading": "kafa vurma", "ball": "top", "famous": "ünlü", "scoring": "gol atma", "difficult": "zor", "goals": "goller", "even": "hatta", "bicycle kicks": "röveşatalar", "entire": "bütün/tüm", "career": "kariyer", "extremely": "son derece", "loyal": "sadık", "refused": "reddetti", "offers": "teklifler", "richer": "daha zengin", "teams": "takımlar", "captain": "kaptan", "national team": "milli takım", "reached": "ulaştı/çıktı", "final": "final", "Even though": "rağmen", "won": "kazandı", "zero": "sıfır", "massive": "büyük", "hero": "kahraman", "because of": "yüzünden", "sportsmanship": "sportmenlik", "warm": "sıcak", "personality": "kişilik" },
    questions: [ {q:"Was Uwe Seeler a short but incredibly strong striker?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he fantastic at heading the ball?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play his entire club career for Hamburger SV?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he refuse offers from richer teams in Italy and Spain?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win five World Cups with Germany?", a_en:"No", a_tr:"Hayır"}, {q:"Is he a massive hero because of his sportsmanship and warm personality?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score difficult goals, even bicycle kicks?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["49_DenisLaw.mp3"] = [{
    text: "Denis Law is a legendary football player from Scotland. He was born in 1940. He played as a striker and was famous for his amazing agility and quick reflexes. Fans called him 'The King' at Old Trafford, the stadium of Manchester United. He played for Manchester United for 11 years and formed a famous attacking trio with Bobby Charlton and George Best. They helped the club win many trophies. In 1964, Law won the Ballon d'Or award. He is the only Scottish player to ever win this prize. He was a fierce competitor and always celebrated his goals with one arm raised in the air. He is also the joint top goalscorer in the history of the Scotland national team.",
    dict: { "legendary": "efsanevi", "striker": "forvet", "famous": "ünlü", "amazing": "şaşırtıcı", "agility": "çeviklik", "quick": "hızlı", "reflexes": "refleksler", "Fans": "taraftarlar", "called": "adlandırdı", "King": "Kral", "stadium": "stadyum", "years": "yıllar", "formed": "kurdu/oluşturdu", "attacking": "hücum eden", "trio": "üçlü", "helped": "yardım etti", "club": "kulüp", "win": "kazanmak", "many": "birçok", "trophies": "kupalar", "won": "kazandı", "award": "ödül", "only": "tek", "Scottish": "İskoç", "ever": "şimdiye kadar", "prize": "ödül", "fierce": "sert/kıyasıya", "competitor": "yarışmacı", "always": "her zaman", "celebrated": "kutladı", "goals": "goller", "arm": "kol", "raised": "kaldırılmış", "air": "hava", "joint": "ortak", "top": "en üst", "goalscorer": "golcü", "history": "tarih", "national team": "milli takım" },
    questions: [ {q:"Was Denis Law famous for his amazing agility and quick reflexes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did fans call him 'The King' at Old Trafford?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he form a famous trio with Bobby Charlton and George Best?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he the only Scottish player to ever win the Ballon d'Or?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he hate to celebrate his goals?", a_en:"No", a_tr:"Hayır"}, {q:"Did he always celebrate his goals with one arm raised in the air?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he the joint top goalscorer in the history of the Scotland national team?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["50_JimmyGreaves.mp3"] = [{
    text: "Jimmy Greaves was a brilliant football player from England. He was born in 1940. He played as a striker and is one of the greatest goalscorers in English football history. He was very calm in front of the goal and could finish easily with both feet. Greaves played for Chelsea, Tottenham Hotspur, and West Ham United. He was the top scorer in the English First Division six times! He scored 357 goals in the top English league, which is a record that stood for many decades. He was part of the England squad that won the 1966 World Cup, although he got injured during the tournament. After he retired, he became a very popular football presenter on television. He passed away in 2021.",
    dict: { "brilliant": "parlak/harika", "striker": "forvet", "greatest": "en büyük", "goalscorers": "golcüler", "history": "tarih", "calm": "sakin", "in front of": "önünde", "goal": "kale/gol", "finish": "bitirmek (gol vuruşu yapmak)", "easily": "kolayca", "both": "her ikisi", "feet": "ayaklar", "top": "en üst", "scorer": "golcü", "Division": "Lig/Küme", "times": "kez", "scored": "attı", "league": "lig", "record": "rekor", "stood": "durdu/geçerli kaldı", "many": "birçok", "decades": "on yıllar", "part": "parça/üye", "squad": "kadro", "won": "kazandı", "although": "rağmen", "injured": "sakatlandı", "during": "sırasında", "tournament": "turnuva", "After": "sonra", "retired": "emekli oldu", "became": "oldu", "popular": "popüler", "presenter": "sunucu", "television": "televizyon", "passed away": "vefat etti" },
    questions: [ {q:"Is Jimmy Greaves one of the greatest goalscorers in English history?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he very calm in front of the goal?", a_en:"Yes", a_tr:"Evet"}, {q:"Could he finish easily with both feet?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he the top scorer in the English First Division six times?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his record of 357 goals break after just one year?", a_en:"No", a_tr:"Hayır"}, {q:"Was he part of the England squad that won the 1966 World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he become a popular football presenter on television?", a_en:"Yes", a_tr:"Evet"} ]
}];
